### ISSUE TITLE
[Task] dto 이름 수정

### ISSUE THREAD

**Issue by leokim1178** [pre-onboarding-backend-E/03-BossRaid-E#29]
### Issue
Group: server
Type: refactor

![image](https://user-images.githubusercontent.com/97543621/178638627-37f9976d-94bc-4bb7-a5dc-a8dbe9a9a6b1.png)

### 상세 내용
- dto 이름을 규칙성 있게 가져가면 좋을것 같습니다
- [ ] createRaid
- [ ] raidEnd
- [ ] raidStatus
- [ ] requestRaid
- [ ] responseRaid
- 코멘트로 의견 공유해서 수정하길 건의드립니다

### 예상 소요 시간
`1h`

### 라벨
- 그룹: `server`
- 우선 사항: `선택`

**Comment by leokim1178** [comment]
raidEnter.dto
raidEnd.dto
raidStatus.dto
raidRankReq.dto
raidRankRes.dto

클래스명은 동일, 파스칼 케이스로

이렇게 바꾸면 좋을거 같은데 어떠세요
급한건 아니고 나중에라도 바꾸면 보기 좋을거 같습니다

**Comment by ymink716** [comment]
바꾼게 더 깔끔하고 좋아보입니다.

**Comment by ParkShinyeong** [comment]
맞춰서 리팩토링 하겠습니다!

**Comment by scvgood287** [comment]
함수명 짓는 방식과 동일하게

createRaid.dto
enterRaid.dto
endRaid.dto

이런 식(~를 ~하는 dto 느낌?)으로
파일명은 카멜 케이스 or 케밥 케이스
클래스 명은 파일명을 파스칼 케이스화 하는 건 어떤가요?
