### ISSUE TITLE
[Task] 스웨거 리스폰스 타입 지정, example, description

### ISSUE THREAD

**Issue by leokim1178** [pre-onboarding-backend-E/03-BossRaid-E#89]
### Issue
Group: server
Type: document

### 상세 내용
- 생각해보니 저희 스웨거 상세 처리를 안했네요
- ApiResponse - type, status, description
- ApiOperation - summary, description 
- 시간 나실 때 다음과 같이 추가해주세요
![image](https://user-images.githubusercontent.com/97543621/179213913-3eee24c1-0009-42da-9398-0d65835888f7.png)
![image](https://user-images.githubusercontent.com/97543621/179213966-0d20bf5a-aa5b-4845-bfbb-32ff28b70065.png)

- [x] @ymink716 
- [x] @everchloe97 
- [x] @scvgood287 
- [x] @ParkShinyeong 
- [x] @leokim1178  

- 전원 완료되면 배포 서버에 업데이트 해놓겠습니다

### 예상 소요 시간
`1h`

### 라벨
- 그룹: `server`
- 우선 사항: `선택`

**Comment by leokim1178** [comment]
저는 오늘은 힘들어서 안할랍니다

**Comment by codeleo-cat** [comment]
저는 api operation만 달겠습니다. request 랑 response 는 기업 측에서 지정해주셔서 설명만 달아도 될 것 같습니다.
